<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="data:image/x-icon;base64,AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAD/hAAA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEREREQAREREREREQAAERERERERAAAREREREREQARERERERAAAAABEREREAAAAAEREQAQAAARAREQAAAAARERERAAAAABEREREQAQAAARARERERAAAAABEREREAAAAAEREREREQAREREREREQAAERERERERAAAREREREREQAREREAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" rel="icon" type="image/x-icon" />
    <link href="//cdn.muicss.com/mui-0.9.26/css/mui.min.css" rel="stylesheet" type="text/css" />
    <link href="lib/js-parsons/parsons.css" rel="stylesheet" />
    <link rel="stylesheet" href="css/master.css">
    <script src="//cdn.muicss.com/mui-0.9.26/js/mui.min.js"></script>
    <script type="text/javascript" src="lib/js-parsons/lib/jquery.min.js"></script>
    <script type="text/javascript" src="js/master.js"></script>

    </script>
  </head>
  <body>
    <header class="mui-appbar mui--z1">
      <div class="mui-container">
        <table width="100%">
          <tr class="mui--appbar-height">
            <td class="mui--text-title"><?=$title ?></td>
            <td align="right">
              <div>
                  <button class="mui-btn" id="feedbackLink">Check</button>
                  <button class="mui-btn mui-btn--danger" id="newInstanceLink">Clear</button>
              </div>
            </td>
          </tr>
        </table>
      </div>
    </header>
